apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.9.3-watch
          ports:
            - containerPort: 8000  # HTTP port
            - containerPort: 8090  # Admin port
          volumeMounts:
            - name: config
              mountPath: /etc/krakend
      volumes:
        - name: config
          configMap:
            name: krakend-config