apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  selector:
    app: krakend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Use ClusterIP for internal access