version: "3.9"
services:
  postgresql:
    image: postgres:16.0
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    networks:
      - accountant
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres-data-16:/var/lib/postgresql/data