version: '3.8'
services:
  # MongoDB for Graylog metadata
  mongo:
    image: mongo:4.2
    networks:
      - accountant
    restart: always
    volumes:
      - mongo_data:/data/db

  # Elasticsearch for storing log messages
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    networks:
      - accountant
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # Graylog server
  graylog:
    image: graylog/graylog:4.2
    networks:
      - accountant
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    environment:
      # generate with: openssl rand -hex 32
      - GRAYLOG_PASSWORD_SECRET=Qwert123456789012
      # generate SHA2 hash: echo -n Passw0rd | sha256sum
      #- GRAYLOG_ROOT_PASSWORD_SHA2=changeme_sha2_here
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    ports:
      - "9000:9000"     # Web interface
      - "12201:12201/udp" # GELF UDP input
      - "1514:1514"     # Syslog TCP input
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal

volumes:
  mongo_data:
  es_data:
  graylog_journal:
